from connnectDB import conn, cursor
from tabulate import tabulate
from load_question import listMenu

reqs = [
    "SELECT adresse_AGENCE FROM AGENCE",
    "SELECT nom_USER FROM USERS WHERE id_PROFIL_PROFIL= 3 ORDER BY nom_USER",
    "SELECT nom_USER , adresse_AGENCE from USERS, AGENCE WHERE USERS.numero_AGENCE_AGENCE = AGENCE.numero_AGENCE AND id_PROFIL_PROFIL = 1",
    "SELECT numero_COMPTE_TRANSACTION, numero_AGENCE_AGENCE FROM `TRANSACTIONS` WHERE numero_AGENCE_AGENCE = 4 ORDER BY montant_TRANSACTION",
    "SELECT SUM(Tab.montant_TRANSACTION) AS somme_TRANSACTION, Tab.nom_USER FROM (SELECT TRANSACTIONS.montant_TRANSACTION, TRANSACTIONS.numero_AGENCE_AGENCE, USERS.nom_USER FROM `TRANSACTIONS` INNER JOIN USERS ON TRANSACTIONS.id_USER_USER = USERS.id_USER WHERE TRANSACTIONS.numero_AGENCE_AGENCE= 7 AND id_TYPE_TYPE = 1 AND USERS.id_PROFIL_PROFIL = 3) AS Tab GROUP BY nom_USER ORDER BY SUM(Tab.montant_TRANSACTION)",
    "SELECT nom_USER, numero_AGENCE_AGENCE FROM USERS WHERE numero_AGENCE_AGENCE = 2 AND id_PROFIL_PROFIL = 4",
    "SELECT Tab.numero_AGENCE,count(Tab.numero_AGENCE) as occurence FROM (SELECT TRANSACTIONS.numero_COMPTE_TRANSACTION, AGENCE.numero_AGENCE FROM `TRANSACTIONS`,  `AGENCE` WHERE TRANSACTIONS.numero_AGENCE_AGENCE = AGENCE.numero_AGENCE ORDER BY AGENCE.numero_AGENCE) as Tab GROUP BY Tab.numero_AGENCE",
    "SELECT date_debut, date_fin, numero_COMPTE_TRANSACTION FROM `ASSOCIER` WHERE id_USER_USER = 1 AND date_debut >= '2021-05-01' AND date_fin <= '2021-05-31'",
    "SELECT id_USER_USER, numero_COMPTE_TRANSACTION FROM `ASSOCIER` WHERE numero_COMPTE_TRANSACTION = 001 AND date_debut >= '2021-01-01' AND date_fin <= '2121-12-31'",
    "SELECT montant_TRANSACTION, id_USER_USER, date_TRANSACTION FROM `TRANSACTIONS` WHERE numero_AGENCE_AGENCE = 001",
    "SELECT ASSOCIER.date_debut, ASSOCIER.date_fin, ASSOCIER.numero_COMPTE_TRANSACTION, USERS.nom_USER , USERS.numero_AGENCE_AGENCE FROM `ASSOCIER`, `USERS` WHERE ( ASSOCIER.date_debut >= '2021-01-01' AND ASSOCIER.date_fin <= '2021-04-30') AND ASSOCIER.id_USER_USER = USERS.id_USER AND USERS.numero_AGENCE_AGENCE = 001",
    "SELECT num_TRANSACTION, montant_TRANSACTION, date_TRANSACTION, numero_COMPTE_TRANSACTION, numero_AGENCE_AGENCE, id_TYPE_TYPE FROM `TRANSACTIONS` WHERE TRANSACTIONS.numero_AGENCE_AGENCE = 7 ORDER BY montant_TRANSACTION",
    "SELECT TRANSACTIONS.montant_TRANSACTION, TRANSACTIONS.frais_TRANSACTION FROM `TRANSACTIONS`, `USERS` WHERE USERS.numero_AGENCE_AGENCE = TRANSACTIONS.numero_AGENCE_AGENCE AND USERS.nom_USER = 'Assane Faye'",
    "SELECT * FROM (SELECT date_TRANSACTION, frais_TRANSACTION, id_TYPE_TYPE FROM `TRANSACTIONS` WHERE numero_AGENCE_AGENCE = 001) as Tab, (SELECT * FROM PART WHERE libelle_PART != 'Systeme') as Par",
    "SELECT * FROM (SELECT date_TRANSACTION, frais_TRANSACTION, id_TYPE_TYPE FROM `TRANSACTIONS`) as Tab, (SELECT * FROM PART WHERE libelle_PART != 'Systeme') as Par WHERE Tab.date_TRANSACTION >= '2021-06-01' AND Tab.date_TRANSACTION <= '2021-12-31'",
    "SELECT numero_AGENCE_AGENCE, count(numero_AGENCE_AGENCE) AS nombre_TRANSACTION, sum(montant_TRANSACTION) AS montant_TOTAL_TRANSCTION FROM TRANSACTIONS WHERE date_TRANSACTION BETWEEN '2021-06-01' AND '2021-06-30' GROUP BY numero_AGENCE_AGENCE",
    "SELECT numero_AGENCE_AGENCE, count(numero_AGENCE_AGENCE) as nombre_TRANSACTION, sum(montant_TRANSACTION) as montant_TOTAL_TRANSCTION FROM TRANSACTIONS WHERE date_TRANSACTION = '2021-08-10'AND id_TYPE_TYPE = 2 GROUP BY numero_AGENCE_AGENCE ORDER BY sum(montant_TRANSACTION)",
    "SELECT montant_TRANSACTION,numero_AGENCE_AGENCE, id_TYPE_TYPE FROM `TRANSACTIONS` WHERE date_TRANSACTION BETWEEN '2021-05-01' AND '2021-05-31' AND id_TYPE_TYPE = 2 ORDER BY montant_TRANSACTION DESC",
    "SELECT montant_TRANSACTION, numero_AGENCE_AGENCE, date_TRANSACTION FROM `TRANSACTIONS` WHERE date_TRANSACTION != '2021-08-10' AND id_TYPE_TYPE != 1",
    "SELECT TRANSACTIONS.date_TRANSACTION ,TRANSACTIONS.numero_AGENCE_AGENCE, USERS.nom_USER FROM `TRANSACTIONS` INNER JOIN USERS ON TRANSACTIONS.id_USER_USER = USERS.id_USER WHERE date_TRANSACTION BETWEEN '2021-05-01' AND '2021-05-31' AND TRANSACTIONS.numero_AGENCE_AGENCE = 001",
    "SELECT TRANSACTIONS.date_TRANSACTION ,TRANSACTIONS.montant_TRANSACTION, TRANSACTIONS.numero_AGENCE_AGENCE, CLIENT.nom_CLIENT, CLIENT.prenom_CLIENT FROM TRANSACTIONS INNER JOIN CLIENT ON TRANSACTIONS.nci_CLIENT_CLIENT = CLIENT.nci_CLIENT WHERE date_TRANSACTION BETWEEN '2021-05-01' AND '2021-05-31' AND TRANSACTIONS.id_TYPE_TYPE = 1 ORDER BY montant_TRANSACTION",
    "SELECT TRANSACTIONS.num_TRANSACTION,TRANSACTIONS.date_TRANSACTION ,TRANSACTIONS.montant_TRANSACTION, TRANSACTIONS.numero_AGENCE_AGENCE, CLIENT.nom_CLIENT, CLIENT.prenom_CLIENT FROM TRANSACTIONS INNER JOIN CLIENT ON TRANSACTIONS.nci_CLIENT_CLIENT = CLIENT.nci_CLIENT WHERE date_TRANSACTION BETWEEN '2021-05-01' AND '2021-05-31' AND TRANSACTIONS.id_TYPE_TYPE = 2 ORDER BY montant_TRANSACTION DESC",
    "SELECT numero_AGENCE_AGENCE, COUNT(TRANSACTIONS.numero_AGENCE_AGENCE)AS nombre_TRANSACTIONS FROM `TRANSACTIONS` WHERE date_TRANSACTION BETWEEN '2021-01-01' AND '2021-12-31' GROUP BY TRANSACTIONS.numero_AGENCE_AGENCE ORDER BY COUNT(TRANSACTIONS.numero_AGENCE_AGENCE) DESC LIMIT 5",
    "SELECT numero_AGENCE_AGENCE, COUNT(TRANSACTIONS.numero_AGENCE_AGENCE) AS nombre_TRANSACTIONS, sum(montant_TRANSACTION) AS montant_TOTAL_TRANSACTION FROM `TRANSACTIONS` WHERE date_TRANSACTION BETWEEN '2021-01-01' AND '2021-12-31' GROUP BY TRANSACTIONS.numero_AGENCE_AGENCE ORDER BY sum(montant_TRANSACTION) ASC LIMIT 5",
    "SELECT Tab.nom_USER, COUNT(Tab.nom_USER) AS nombre_de_Fois , sum(Tab.montant_TRANSACTION) AS montant_TOTAL_TRANSACTION FROM (SELECT montant_TRANSACTION, date_TRANSACTION, TRANSACTIONS.numero_AGENCE_AGENCE, USERS.nom_USER FROM TRANSACTIONS INNER JOIN USERS ON TRANSACTIONS.id_USER_USER= USERS.id_USER WHERE TRANSACTIONS.numero_AGENCE_AGENCE = 7 AND USERS.id_PROFIL_PROFIL= 4) AS Tab GROUP BY Tab.nom_USER ORDER BY sum(Tab.montant_TRANSACTION) DESC LIMIT 1",
]

Libs_Header = [
    ['adresse_AGENCE'],
    ['nom_USER'],
    ['nom_USER' , 'adresse_AGENCE'],
    ['numero_COMPTE_TRANSACTION', 'numero_AGENCE_AGENCE'],
    ['somme_TRANSACTION', 'nom_USER'],
    ['nom_USER', 'numero_AGENCE_AGENCE'],
    ['numero_AGENCE' ,'Occurences'],
    ['date_debut', 'date_fin', 'numero_COMPTE_TRANSACTION'],
    ['id_USER', 'numero_COMPTE_TRANSACTION'],
    ['montant_TRANSACTION', 'id_USER_USER', 'date_TRANSACTION'],
    ['date_debut', 'date_fin', 'numero_COMPTE_TRANSACTION', 'nom_USER' , 'numero_AGENCE_AGENCE'],
    ['num_TRANSACTION', 'montant_TRANSACTION', 'date_TRANSACTION', 'numero_COMPTE_TRANSACTION', 'numero_AGENCE_AGENCE', 'id_TYPE_TYPE'],
    ['montant_TRANSACTION', 'Frais_TRANSACTION'],
    [''],
    [''],
    ['numero_AGENCE_AGENCE', 'nombre_TRANSACTION', 'montant_TOTAL_TRANSCTION'],
    ['numero_AGENCE_AGENCE', 'nombre_TRANSACTION', 'montant_TOTAL_TRANSCTION'],
    ['montant_TRANSACTION','numero_AGENCE', 'id_TYPE_TYPE'],
    ['montant_TRANSACTION', 'numero_AGENCE', 'date_TRANSACTION'],
    ['date_TRANSACTION' ,'numero_AGENCE', 'nom_USER'],
    ['date_TRANSACTION' , 'montant_TRANSACTION', 'numero_AGENCE', 'nom_CLIENT', 'prenom_CLIENT'],
    ['num_TRANSACTION', 'date_TRANSACTION' , 'montant_TRANSACTION', 'numero_AGENCE' , 'nom_CLIENT', 'prenom_CLIENT'],
    ['numero_AGENCE', 'nombre_TRANSACTIONS'],
    ['numero_AGENCE', 'nombre_TRANSACTIONS', 'montant_TOTAL_TRANSACTION'],
    ['nom_USER', 'nombre_de_Fois' , 'montant_TOTAL_TRANSACTION']
]



def query_sql(ind):
    
    # print(listMenu[ind-1])
    cursor.execute(reqs[ind - 1])
    result =  cursor.fetchall()
    print(tabulate(result, headers = Libs_Header[ind - 1], tablefmt = 'psql'))

